/**
 * SVG sanitization — DOMPurify 封装，防止 XSS 注入。
 *
 * LLM 输出的 SVG 可能包含 <script>、on* 事件属性、javascript: URL 等攻击向量。
 * 使用 DOMPurify SVG profile 做白名单过滤，只保留安全的 SVG 标签和属性。
 */

import DOMPurify from "dompurify";

const ALLOWED_SVG_TAGS = [
  "svg",
  "g",
  "path",
  "rect",
  "circle",
  "ellipse",
  "line",
  "polyline",
  "polygon",
  "text",
  "tspan",
  "textPath",
  "defs",
  "use",
  "symbol",
  "clipPath",
  "mask",
  "marker",
  "linearGradient",
  "radialGradient",
  "stop",
  "filter",
  "feGaussianBlur",
  "feOffset",
  "feMerge",
  "feMergeNode",
  "feFlood",
  "feComposite",
  "feBlend",
  "feColorMatrix",
  "feDropShadow",
  "feMorphology",
  "feTurbulence",
  "feDisplacementMap",
  "image",
  "title",
  "desc",
  "pattern",
] as const;

const FORBID_TAGS = ["script", "foreignObject", "iframe", "object", "embed"];

const FORBID_ATTR = [
  "onload",
  "onerror",
  "onclick",
  "onmouseover",
  "onmouseout",
  "onmouseenter",
  "onmouseleave",
  "onmousedown",
  "onmouseup",
  "onfocus",
  "onblur",
  "onchange",
  "onsubmit",
  "onkeydown",
  "onkeyup",
  "onkeypress",
  "onanimationstart",
  "onanimationend",
  "ontouchstart",
  "ontouchend",
];

export function sanitizeSvg(raw: string): string {
  if (!raw || !raw.trim()) return "";

  return DOMPurify.sanitize(raw, {
    USE_PROFILES: { svg: true, svgFilters: true },
    ADD_TAGS: [...ALLOWED_SVG_TAGS],
    FORBID_TAGS,
    FORBID_ATTR,
    ADD_ATTR: [
      "viewBox",
      "preserveAspectRatio",
      "xmlns",
      "xmlns:xlink",
      "xlink:href",
      "href",
      "fill",
      "stroke",
      "stroke-width",
      "stroke-linecap",
      "stroke-linejoin",
      "stroke-dasharray",
      "stroke-dashoffset",
      "opacity",
      "fill-opacity",
      "stroke-opacity",
      "transform",
      "d",
      "points",
      "x",
      "y",
      "x1",
      "y1",
      "x2",
      "y2",
      "cx",
      "cy",
      "r",
      "rx",
      "ry",
      "width",
      "height",
      "font-size",
      "font-family",
      "font-weight",
      "text-anchor",
      "dominant-baseline",
      "alignment-baseline",
      "letter-spacing",
      "word-spacing",
      "text-decoration",
      "clip-path",
      "mask",
      "filter",
      "marker-start",
      "marker-mid",
      "marker-end",
      "gradientUnits",
      "gradientTransform",
      "spreadMethod",
      "offset",
      "stop-color",
      "stop-opacity",
      "patternUnits",
      "patternTransform",
      "markerWidth",
      "markerHeight",
      "refX",
      "refY",
      "orient",
      "overflow",
      "stdDeviation",
      "dx",
      "dy",
      "result",
      "in",
      "in2",
      "mode",
      "flood-color",
      "flood-opacity",
      "color-interpolation-filters",
    ],
  });
}
